title = "Cyber AI"
baseURL = "http://cyberai.tech"
tags = ["cyber", "security", "artificial intelligence", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
publishDir = "docs"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "tomanistor"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "Artificial Intelligence for Cyber Security"
    author = "Evan Gaustad"
    description = "Exploring new techniques to combat cyber threats"
    logoBig = "/images/cyber-ai-logo.png"
    logoSmall = "/images/cyber-ai-logo.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/cyber-ai-logo"
    twitter = "egaustad3"
    linkedin = "Evan Gaustad"
    github = "egaus"
    email = ""
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
